const fs = require('fs')
const path = require('path')

function mkdir(trg) {
    const trgPath = path.join(__dirname, 'static', 'vendor', trg)
    fs.mkdirSync(trgPath, { recursive: true })
}
function copy(src, trg) {
    const srcPath = path.join(__dirname, 'node_modules', src)
    const trgPath = path.join(__dirname, 'static', 'vendor', trg)
    fs.copyFileSync(srcPath, trgPath)
}

copy('lodash/lodash.min.js', 'lodash.min.js')
copy('jquery/dist/jquery.min.js', 'jquery.min.js')
copy('dayjs/dayjs.min.js', 'dayjs.min.js')
copy('dayjs/locale/de.js', 'dayjs.locale.de.js')
copy('dayjs/plugin/utc.js', 'dayjs.plugin.utc.js')
copy('dayjs/plugin/timezone.js', 'dayjs.plugin.timezone.js')
copy('bootstrap/dist/js/bootstrap.min.js', 'bootstrap.min.js')
copy('bootstrap/dist/js/bootstrap.min.js.map', 'bootstrap.min.js.map')
copy('bootstrap/dist/css/bootstrap.min.css', 'bootstrap.min.css')
copy('bootstrap/dist/css/bootstrap.min.css.map', 'bootstrap.min.css.map')
mkdir('leaflet')
copy('leaflet/dist/leaflet.js', 'leaflet/leaflet.js')
copy('leaflet/dist/leaflet.js.map', 'leaflet/leaflet.js.map')
copy('leaflet/dist/leaflet.css', 'leaflet/leaflet.css')
mkdir('leaflet/images')
copy('leaflet/dist/images/marker-icon.png', 'leaflet/images/marker-icon.png')
copy('leaflet/dist/images/marker-icon-2x.png', 'leaflet/images/marker-icon-2x.png')
copy('leaflet/dist/images/marker-shadow.png', 'leaflet/images/marker-shadow.png')
copy('vega/build/vega.min.js', 'vega.min.js')
copy('vega/build/vega.min.js.map', 'vega.min.js.map')
copy('vega-lite/build/vega-lite.min.js', 'vega-lite.min.js')
copy('vega-lite/build/vega-lite.min.js.map', 'vega-lite.min.js.map')
copy('vega-embed/build/vega-embed.min.js', 'vega-embed.min.js')
copy('vega-embed/build/vega-embed.min.js.map', 'vega-embed.min.js.map')

// mkdir('pickadate')
// copy('pickadate/lib/compressed/picker.js', 'pickadate/picker.js')
// copy('pickadate/lib/compressed/picker.date.js', 'pickadate/picker.date.js')
// copy('pickadate/lib/compressed/picker.time.js', 'pickadate/picker.time.js')
// mkdir('pickadate/themes')
// copy('pickadate/lib/compressed/themes/classic.css', 'pickadate/themes/classic.css')
// copy('pickadate/lib/compressed/themes/classic.date.css', 'pickadate/themes/classic.date.css')
// copy('pickadate/lib/compressed/themes/classic.time.css', 'pickadate/themes/classic.time.css')
// mkdir('pickadate/translations')
// copy('pickadate/lib/compressed/translations/de_DE.js', 'pickadate/translations/de_DE.js')

mkdir('fontawesome')
copy('@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff', 'fontawesome/fa-regular-400.woff')
copy('@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff2', 'fontawesome/fa-regular-400.woff2')
copy('@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff', 'fontawesome/fa-solid-900.woff')
copy('@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2', 'fontawesome/fa-solid-900.woff2')
copy('@fortawesome/fontawesome-free/css/fontawesome.min.css', 'fontawesome/fontawesome.min.css')
